include:
  - path: ./docker-compose.dev.yml # spec without ports exposed


services:
  # expose the ports for users without dev container
  api:
    ports:
      - "8000:8000"
    
  mock:
    ports:
      - "8001:8001"

  prefect-server:
    ports:
      - "4200:4200"

  frontend:
    ports:
      - "2718:2718"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  azurite:
    ports:
      - "10000:10000"
