services:
  # override the ports exposed in docker compose and handle port forwarding with devcontainer.json
  prefect-server:
    ports: []
  
  api:
    ports: [] 

  mock:
    ports: []

  frontend:
    ports: []